.TH "md__c_h_a_n_g_e_l_o_g" 3 "Fri Dec 18 2015" "Version v1.0.0" "Numerus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_h_a_n_g_e_l_o_g \- CHANGELOG 
\fIAll notable changes to\fP Numerus \fIwill be documented in this file\&.\fP
.PP
.PP
.PP
.SH "v1\&.0\&.0 "
.PP
.PP
.SS "Added "
.PP
.IP "\(bu" 2
Bidirectional conversion short integer <-> roman numerals (as string)
.IP "\(bu" 2
Syntax check of roman numerals
.IP "\(bu" 2
Comparison of two roman numerals
.IP "\(bu" 2
Allocation of array with all roman numerals
.IP "\(bu" 2
Creation of SQLite3 database with all roman numerals and their values
.IP "\(bu" 2
Custom error codes
.IP "\(bu" 2
Documentation of all functions and variables with doxygen
.IP "\(bu" 2
BSD 3-clause license, Changelog and Readme files 
.PP

